### PR TITLE
feat(*): Add opentrons app

### PR DESCRIPTION
**Pull request by sfoster1**
Adds a recipe for the opentrons js app running in an electron container and specifying all required dependencies and installs it in the opentrons-ot3-image along with its  requirements and dependencies.

Todo:
- [x] package robot app binary to /opt
- [x] window system/compositor basic bringup (wayland/weston + xwayland)
- [x] gpu/drm bringup
- [x] correct kernel cmdline modeset since hotplug doesn't work
- [x] systemd unit or wayland autostart to come up fullscreen

Our robot system runs on a toradex verdin, which is an imx8mm with an integrated graphics capability. That graphics capability renders to a DSI format output. On the development board, that goes to an HDMI adapter; on our real machine, it will go to an LVDS adapter to a touchscreen.

Running the app on an ot3 or on a verdin devkit requires changes to all those areas.

- We needed to switch our distro and machine selection and configuration to the versions that configure graphics, and build the graphics support packages. That means support for a version of egl (mesa and egl2, from freescale's upstream); this gives the kernel render capabilities through something other than a framebuffer.
- We need to tell the system what kind of display to drive, because while normally that would happen through an HDMI (or displayport, etc) driver detecting a display and pulling config for it through a system called EDID, DSI doesn't actually have any of that, so we have to do what's called modesetting through a hardcoded interface string that we give to the kernel commandline. That passes through uboot (and is stored in the uboot env blob that lives in the special carveout at the beginning of emmc) and that needs to be set during first-flash, with a wrapup script that gets run by the toradex easyinstaller
- While in most embedded circumstances we'd write a display program using a framework like QT that would handle all the userspace rendering - whether through a gl context, a middleware like gtk, or a driver like egl; or through interface with the kernel's drm (direct render management) layer - we're using electron framework, whose job first and foremost is to make applications run on normal computers. That means it expects to interact with a desktop system rather than handling its own rendering (chromium has a drm backend output but it's hard to get to work with electron). Because of the restrictions on what upstream has implemented, that means we need weston. Weston is a reference implementation of a wayland-compatible compositor, which is the system replacing X11 in linux userspace circles. It provides draw primitives like "i'd like a window with a menu" and in many circumstances support for normal desktop things like overlapping windows, icons, system menu bars, and so on.
- But we don't actually want a desktop experience, we just want to run the app. Luckily weston supports pluggable shells, which provide APIs and customize the interactions on this kind of level. We want the kiosk shell, which runs an app fullscreen as the primary method of interaction while still allowing various popups. This in turn requires a bunch of config overrides
- Once we have all of that, we need to build the app js packages, which we pull from the monorepo and use normal electron-builder (along with a big bundle of dependencies)

### CODE REVIEW

**Review by DerekMaggio — COMMENTED** [review]
So are the `bb` files generated or are you writing them?

**Comment by sfoster1** [comment]
> So are the `bb` files generated or are you writing them?

I write them. The robot-app.bb is mostly original, the others are copied from the bsp (and I should delete the qt5 one probably). There are various tools that provide an initial scaffolding but it's also like 5 lines. https://wiki.yoctoproject.org/wiki/Building_your_own_recipes_from_first_principles is a doc on how (although I mostly pattern-matched from other recipes I've seen).

**Comment by DerekMaggio** [comment]
Okay that makes sense. Thank you :)

**Review by sotaoverride — APPROVED** [review]
I just was trying to remember if wayland and x11 depend on qt5 or is it the other way around?

**Comment by sfoster1** [comment]
> I just was trying to remember if wayland and x11 depend on qt5 or is it the other way around?

other way around.

i think i don't want to merge this yet because i want to see if we can get https://github.com/Opentrons/opentrons/pull/8226 in and then drop the xcompat layer entirely and roll with wayland/egl direct.

**Review by amitlissack — APPROVED** [review]
I can't say that this is approval is with a ton of understanding of what's going on, but it nothing looks insane.

**Review by sotaoverride — COMMENTED** [review]
I cant remember what layer recipes-devtools was, and [OE layer index](https://layers.openembedded.org/layerindex/branch/master/layers) isnt helping most the the patches seem to be for a nodejs recipe. Can we have one recipe with all the patches applied to it have that live under meta-opentrons/nodejs or something? Or am i missing something? Did we some some devtool co

**Review by sotaoverride — APPROVED** [review]
Thanks for pointing me to nodejs recipes being brought in here [meta-oe/recipes-dectools/nodejs](https://github.com/openembedded/meta-openembedded/tree/master/meta-oe/recipes-devtools/nodejs). Spent some time going over robot-app recipe, lgtm!

**Pull request merged**
